
/**
 * AUTO-GENERATED FILE
 * This file is generated by the generate-icon-mapping.js script.
 */
import dynamic from "next/dynamic";

export const iconMapping = {
  "next": dynamic(() => import(/* webpackChunkName: "Icon-next" */ "@/icons/next.svg")),
  "vercel": dynamic(() => import(/* webpackChunkName: "Icon-vercel" */ "@/icons/vercel.svg")),
};
